💿 Storage: Pin / Unpin object
okp4/contracts pull request #126
Opened 2023-02-28 12:44 UTC by bdeneux

🚧

2023-03-02 14:22 UTC, bdeneux commented
> @bdeneux Regarding the behavior when pinning already pinned object and unpinning not yet pinned object I agree with you, as it changes nothing in the state, to consider those messages successful, making them as no-op.
> 
> @ccamel Your opinion about that? We'll need to update the specifications accordingly.

@amimart @ccamel Sorry, my bad, after checking, the specification already indicate this behavior :  
```go
/// # PinObject
    /// PinObject pins the object in the bucket for the considered sender. If the object is already pinned
    /// for the sender, this is a no-op.
    /// While an object is pinned, it cannot be removed from the storage.
```
```go 
/// # UnpinObject
    /// UnpinObject unpins the object in the bucket for the considered sender. If the object is not pinned
    /// for the sender, this is a no-op.
    /// The object can be removed from the storage if it is not pinned anymore.
```
So it's ok for the PinObject. My question now is about the `UnpinObject`, what do you think if we try to unpin a not found object id, since the pin is not found on the Pins state, this will be also a no-op, do we need instead to return that the object is not found (keeping in mind that this need to ask the state twice instead of once if the object exist) ?

2023-03-02 14:34 UTC, amimart commented
@bdeneux In the case we try to unpin a non existing object, I would tend to make it an error case, even if it has a little more cost than considering it a no-op. Because a successful unpin of an object could suggest the existence of it.

2023-03-08 18:09 UTC, amimart requested changes
Nice piece! 💪 

I just noted small enhancement ways :)

2023-03-08 18:09 UTC, amimart commented on contracts/cw-storage/src/contract.rs
> +                    .add_attribute("id", object_id))
The response code is duplicated, we can declare it first and use it as it is done in the unpin 😉

2023-03-08 18:31 UTC, amimart requested changes

2023-03-08 18:31 UTC, amimart commented on contracts/cw-storage/src/contract.rs
> +        )?;
We may load the bucket after updating the object, it'll reduce the gas consumption in case the object doesn't exists.

2023-03-09 10:25 UTC, amimart approved these changes
Sounds pretty great! 🚀

2023-03-09 13:41 UTC, ccamel approved these changes
LGTM! :+1:

2023-03-09 13:55 UTC, merged