💿 Storage : Queries
okp4/contracts pull request #129
Opened 2023-03-01 22:46 UTC by amimart

Implements `Objects` & `ObjectPins` query.

2023-03-10 09:01 UTC, bdeneux requested changes
Wonderful, nice work ! 👍

I just suggest some modification about Pagination serialization / deserialization / validation. Is just to open discussion about it. Especially if the validation should be done on the state object (`Pagination`) or msg object (`PaginationConfig`), allowing to use the built-in rust trait.

2023-03-10 13:33 UTC, amimart commented
> I just suggest some modification about Pagination serialization / deserialization / validation. Is just to open discussion about it. Especially if the validation should be done on the state object (`Pagination`) or msg object (`PaginationConfig`), allowing to use the built-in rust trait.

I implemented the validation on the msg part to do it at the interface level, but since the validation derives directly from business logic the `TryFrom` implementation on the state side seems relevant, I actually find it much more elegant 👍

2023-03-10 14:00 UTC, bdeneux commented on contracts/cw-storage/src/pagination.rs
> +pub struct PaginationHandler<'a, T, PK>
Yes ! That seem good to wait 👍

2023-03-10 14:15 UTC, amimart commented on contracts/cw-storage/src/msg.rs
> +    pub max_page_size: Option<u32>,
That would be better indeed, but it has an impact on the generated schema, making the fields mandatory instead of optional..

2023-03-10 14:24 UTC, bdeneux commented on contracts/cw-storage/src/msg.rs
> +    pub max_page_size: Option<u32>,
Ahh, that annoying 😅. I didn't thought about schema generation... 😭

2023-03-13 08:47 UTC, amimart commented on contracts/cw-storage/src/msg.rs
> +    pub max_page_size: Option<u32>,
I thus propose to let it as is for now, If you're ok with that @bdeneux

2023-03-13 10:56 UTC, bdeneux commented on contracts/cw-storage/src/msg.rs
> +    pub max_page_size: Option<u32>,
It's ok for me !

2023-03-21 13:30 UTC, ccamel approved these changes
Let's go! 🚀

2023-03-21 13:32 UTC, merged