Use binary key as object id
okp4/contracts pull request #219
Opened 2023-05-11 11:49 UTC by bdeneux

2023-05-23 05:59 UTC, amimart requested changes
That's a nice piece thx! 💪 

I just pointed out a little something :)

2023-05-23 05:59 UTC, amimart commented on contracts/okp4-objectarium/src/crypto.rs
> +impl From<Hash> for Cow<'_, Hash> {
I think we can remove this implementation, in the other direction as well :)

2023-05-23 08:50 UTC, amimart approved these changes

2023-05-24 13:04 UTC, ccamel approved these changes
LGTM! Thanks 👍

2023-05-24 13:05 UTC, ccamel commented
@bdeneux your branch is in conflict. Can you rebase? thanks 🙏

2023-05-24 13:19 UTC, merged