Feat/describe
okp4/contracts pull request #254
Opened 2023-06-15 21:26 UTC by ccamel

Closes #215 - providing the implementation for the `Describe` query message handling.

## Details

tbd

2023-06-19 07:05 UTC, amimart requested changes
That's a nice piece thx! 🙏 

Just suggested a tiny improvement :)

2023-06-19 12:46 UTC, ccamel commented on contracts/okp4-cognitarium/src/contract.rs
> +        }
Ah ah, well spotted!

2023-06-22 15:36 UTC, amimart approved these changes

2023-06-22 16:58 UTC, ccamel commented
Thanks @bdeneux for increasing test coverage :relaxed:

2023-06-23 07:27 UTC, bdeneux approved these changes
Nice ! That seems good :) 😁

2023-06-23 07:45 UTC, merged