Feat/objectarium lzma compression
okp4/contracts pull request #296
Opened 2023-07-31 12:49 UTC by ErikssonJoakim

This PR adds the LZMA compression algorithm to the Objectarium smart-contract, a lossless compression with high compression ratio!
- #263 

No tests have been added for the decompression. This could be added at another time with test for snappy decompression as well

2023-08-01 15:11 UTC, ccamel requested changes

2023-08-01 15:11 UTC, ccamel commented on contracts/okp4-objectarium/src/compress.rs
> +    }
No need for parenthesis.

```suggestion
        lzma_rs::lzma_compress(&mut reader, &mut writer)?;
```

2023-08-01 15:11 UTC, ccamel commented on contracts/okp4-objectarium/src/compress.rs
> +    }
No need for parenthesis.

```suggestion
        lzma_rs::lzma_decompress(&mut reader, &mut writer)?;
```

2023-08-02 09:18 UTC, amimart approved these changes
Looks good! 😉

2023-08-02 09:20 UTC, ccamel approved these changes
Great! Thanks :+1:

2023-08-02 09:22 UTC, merged