Feat/delete implementation
okp4/contracts pull request #304
Opened 2023-08-03 13:21 UTC by ccamel

This PR brings the (missing) DeleteData message implementation in the Cognitarium smart contract, which provides the functionality to delete triples from the contract's state.

2023-08-07 12:12 UTC, ccamel commented
Status: implementation done. Missing tests.

2023-08-30 13:46 UTC, ccamel commented
Rebased to include #311 and #322 (among others).

2023-09-05 16:12 UTC, amimart requested changes

2023-09-05 16:15 UTC, ccamel commented on contracts/okp4-cognitarium/src/storer/engine.rs
> +        self.store.stat.triple_count -= Uint128::one();
That's a good catch. Thanks :relieved:

2023-09-05 16:17 UTC, amimart approved these changes
Looks good! 🚀

2023-09-06 07:49 UTC, bdeneux approved these changes
Seems good 👍 Nice !

2023-09-06 08:35 UTC, merged