Smart contract scaffolding
okp4/contracts pull request #333
Opened 2023-08-28 07:40 UTC by ccamel

This PR introduces a basic scaffold mechanism for smart contracts to facilitate the implementation of new smart contracts. This PR doesn't do much apart from copying (and substituting the project name) into the contract directory. But this can easily be improved as required.

Scaffolding uses [ffizer](https://github.com/ffizer/ffizer) for doing the job.

2023-08-28 15:29 UTC, ccamel commented
Following @ErikssonJoakim's review, it seems that installing via the crate demands a Rust version more advanced than what's needed for compiling smart contracts. Additionally, installation with curl leads to binary resolution issues in the `PATH` based on the environment. Therefore, it's best to treat the `ffizer` tool as a necessary prerequisite for executing the task. Developers are responsible for its installation (as detailed in the `README.md`).

2023-08-28 15:44 UTC, ErikssonJoakim approved these changes
Great 😃 Once we've catched up on the rustc version we can implement the install

2023-08-29 08:27 UTC, bdeneux requested changes
Nice tool ! 👍 Just a little changes requested to remove the unnecessary dependencies at the beginning of the smart contract development.

2023-08-29 08:27 UTC, bdeneux commented on templates/okp4-smart-contract/{{ contract_name }}/Cargo.ffizer.hbs.toml
> +url = "2.4.0"
```suggestion
```
This one too

2023-08-29 10:04 UTC, bdeneux approved these changes

2023-08-29 10:56 UTC, merged