chore: update @fadroma/schema to 1.1.0
okp4/contracts pull request #342
Opened 2023-08-31 07:54 UTC by egasimus

This adds a footer to generated docs which contains:

* Name of schema file used to generate schema
* First 16 characters of SHA256 hash of source schema file
* Link to https://www.npmjs.com/package/@fadroma/schema and version used
* Link to https://fadroma.tech/

I hope the latter two are acceptable. We're trying to raise awareness of our toolkit's existence, and would be happy to collaborate more closely with your team in the future.

2023-09-01 13:24 UTC, antho31 commented
Hello @egasimus

The following is all about suggestions, and fully open to discussions.

We understand your awareness concerns, but we are looking to work in another way to value/reward contributors. 

We better prefer to grant `fadroma`'s use as a [Builder program's open contribution](https://nemeton.okp4.network/builders/challenges#challenges) (the 4th challenge of "Invoke the power of Dagda" part, eligible up to 100 000 $KNOW). 
And even for deeper collaboration, what about a similar package as well as there is with Secret, for OKP4? We saw OKP4 mentioned in the [Medium article](https://medium.com/@fadroma/fadroma-somewhat-reluctantly-joins-medium-6dfd278bab62) :)

2023-09-07 09:05 UTC, antho31 commented
Alright, just sent you a mail :)

2023-09-07 13:41 UTC, bdeneux requested changes
Thanks 🙏 ! 
By changing version, the new documentation generated differ and linter doesn't accept if you don't commit this new documentation. 
If you can please commit the new generated documentation so that it can be up to date on the docs repository 😇: 
```
cargo make docs-generate
```

2023-09-08 09:29 UTC, amimart approved these changes
Thx! 🙏

2023-09-08 09:31 UTC, ccamel approved these changes
:clap: Thanks

2023-09-08 09:32 UTC, bdeneux approved these changes
Thanks 🙏!

2023-09-08 09:32 UTC, merged